### ISSUE TITLE
Code review before publishing

### ISSUE THREAD

**Issue by Planeshifter** [compute-io/minkowski-distance#1]

**Comment by kgryte** [comment]
@Planeshifter I have stubbed the module to use the Euclidean, Manhattan, and Chebyshev distance modules. Once those have been vetted and published, they can be used as deps for this module. Only then can the tests be finished.

**Comment by kgryte** [comment]
We will also need to resolve the `p <= 0` case and whether we should support it.

**Comment by kgryte** [comment]
I am fine with this module being published, as is. We can create a new issue which poses the question as to whether or not to support `p <= 0`. Any objections?

**Comment by Planeshifter** [comment]
no, not at all. sounds good to me. go ahead and publish!

**Comment by kgryte** [comment]
Done.
